services:
  # Production backend service
  - type: web
    name: docathome-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DEFAULT_SEED_PASSWORD
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  # Staging backend service
  - type: web
    name: docathome-backend-staging
    runtime: node
    branch: develop
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: staging
      - key: MONGO_URI
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DEFAULT_SEED_PASSWORD
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false

databases:
  # Production database
  - name: docathome-db
    databaseName: docathome
    user: docathome

  # Staging database
  - name: docathome-db-staging
    databaseName: docathome_staging
    user: docathome